export type ContentStatus = 'draft' | 'published' | 'archived';
export type ContentCategory = 'news' | 'blog' | 'press';

/**
 * Form data that users fill in
 * This is what the form collects from user input
 * 
 * Note: Does NOT include:
 * - created_at (auto-generated by server)
 * - updated_at (auto-generated by server)
 * - read_time_minutes (auto-calculated from content)
 * - id (generated by server after submission)
 */
export interface CMSFormData {
  heading: string;
  description: string;
  slug: string;
  content: string;
  keywords: string[];
  author: string;
  status: ContentStatus;
  category: ContentCategory;
  featured_image: string;
  is_featured: boolean;
  tags: string[];
  seo_title: string;
  seo_description: string;
}

/**
 * Complete CMS content data including server-generated fields
 * This is what the API returns after successful submission
 */
export interface CMSContentData extends CMSFormData {
  id: string;                    // Generated by server
  created_at: string;            // Auto-generated timestamp (ISO format)
  updated_at?: string;           // Auto-generated on updates (ISO format)
  read_time_minutes: number;     // Auto-calculated from content length
}

/**
 * Props for CMSForm component
 */
export interface CMSFormProps {
  initialData?: Partial<CMSFormData>;
  onSubmit: (data: CMSFormData) => Promise<CMSContentData>;
}

/**
 * Generic API response wrapper
 */
export interface ApiResponse<T = unknown> {
  success: boolean;
  message?: string;
  data?: T;
  error?: string;
}

/**
 * API response for content submission
 */
export type SubmitContentResponse = ApiResponse<CMSContentData>;

/**
 * API response for content fetching
 */
export type FetchContentResponse = ApiResponse<CMSContentData>;

/**
 * API response for content update
 */
export type UpdateContentResponse = ApiResponse<{
  id: string;
  updated_at: string;
}>;

/**
 * API response for content deletion
 */
export type DeleteContentResponse = ApiResponse<{
  message: string;
}>;