import { Controller, type Control } from 'react-hook-form';
import { 
  Box,
  Select,
  MenuItem,
  FormControl,
  InputLabel,
  FormHelperText,
  Typography,
  Alert
} from '@mui/material';
import type { CMSFormData } from '../../types/cms.types';

export interface MetadataFieldsProps {
  control: Control<CMSFormData>;
}

/**
 * Metadata Fields Section
 * 
 * Contains:
 * - status: Publication status (draft/published/archived)
 * - category: Content category (news/blog/press)
 * 
 * Note: The following fields are auto-generated by the server:
 * - created_at: Automatically set when content is created
 * - updated_at: Automatically set when content is updated
 * - read_time_minutes: Calculated from content length (~200 words/minute)
 */
export function MetadataFields({ control }: MetadataFieldsProps) {
  return (
    <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
      {/* Info Alert */}
      <Alert severity="info" sx={{ mb: 1 }}>
        <Typography variant="caption">
          <strong>Note:</strong> Creation date, update date, and reading time will be automatically generated when you submit.
        </Typography>
      </Alert>

      {/* Status Field */}
      <Controller
        name="status"
        control={control}
        render={({ field, fieldState }) => (
          <FormControl fullWidth required error={!!fieldState.error}>
            <InputLabel id="status-label">Status</InputLabel>
            <Select
              {...field}
              labelId="status-label"
              label="Status"
            >
              <MenuItem value="draft">Draft</MenuItem>
              <MenuItem value="published">Published</MenuItem>
              <MenuItem value="archived">Archived</MenuItem>
            </Select>
            {fieldState.error && (
              <FormHelperText>{fieldState.error.message}</FormHelperText>
            )}
            {!fieldState.error && (
              <FormHelperText>
                Select the publication status of this content
              </FormHelperText>
            )}
          </FormControl>
        )}
      />

      {/* Category Field */}
      <Controller
        name="category"
        control={control}
        render={({ field, fieldState }) => (
          <FormControl fullWidth required error={!!fieldState.error}>
            <InputLabel id="category-label">Category</InputLabel>
            <Select
              {...field}
              labelId="category-label"
              label="Category"
            >
              <MenuItem value="news">News</MenuItem>
              <MenuItem value="blog">Blog</MenuItem>
              <MenuItem value="press">Press</MenuItem>
            </Select>
            {fieldState.error && (
              <FormHelperText>{fieldState.error.message}</FormHelperText>
            )}
            {!fieldState.error && (
              <FormHelperText>
                Choose the content category
              </FormHelperText>
            )}
          </FormControl>
        )}
      />
    </Box>
  );
}